### ISSUE TITLE
Error while using older Cmake version

### ISSUE THREAD

**Issue by donank** [berndporr/fastcgi_json_cpp_api#1]
One of my teammates tried to build the project in an older Cmake version (3.5.1) and got the following error:
```
 INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "PUBLIC_HEADER" is not allowed.
```
Apparently, this was a requirement prior to CMake 3.19 update. [Link](https://discourse.cmake.org/t/how-to-find-current-interface-library-property-whitelist/4784) to a related thread on cmake forums talking about the issue. Attaching a screenshot of the error. 

![Screenshot from 2022-04-08 04-30-34](https://user-images.githubusercontent.com/14325084/162588391-beaa79cd-0cd3-40f1-af41-cb6cba7afde3.png)

**Comment by berndporr** [comment]
gcc is about 10 years old and cmake about 8years out of date. If you can fix it without conditionals then feel free to submit a pull request but otherwise it's just too old.
https://askubuntu.com/questions/1087150/install-gcc-5-on-ubuntu-18-04
https://www.kitware.com/cmake-3-5-1-available-for-download/
